
server:
  port: 9001

spring:
  application:
    name: content-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mariadb://13.209.13.28:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: taekyung
    password: rlaxorud

eureka:
  instance:
#    hostname: localhost  # PC hosts 파일 문제
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.uplus.sdcontent: DEBUG